#!/bin/bash
{ set +x; } 2>/dev/null
echo "Setting up nvm"
# install node if we are on on cloudbees cloud node
if [[ $NODE_LABELS =~ .*lxc-fedora.* ]]
then
  curl -sS  https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | ( bash || true )
  source ~/.nvm/nvm.sh
  nvm install stable &> nvm-install.log
else
  source ~/.nvm/nvm.sh
fi

# print node and npm versions
echo "configuring node"
nvm use stable

# installing global gulp
npm install -g gulp

# display setting
export DISPLAY=:1
