#!/bin/bash
{ set -x; } 2>/dev/null

# when old syle structure is detected, delete everything
if [ -f gulpfile.js ]; then rm -rf ./*; fi

export APPIUM_ROOT="$(pwd)/build"
rm -rf "${APPIUM_ROOT}"
mkdir -p "${APPIUM_ROOT}"

if [ -d appium-ci ]
then
  echo 'appium-ci already exists, updating'
  pushd appium-ci
  git fetch origin
  git reset --hard origin/master
  popd
else
  echo "appium-ci doesn't exist, creating"
  git clone https://github.com/appium/appium-ci.git
fi
pushd appium-ci/jenkins-tools
